######################################################
# Openscope dataset 
######################################################

DATASET = "allen_brain_observatory_calcium"

RAW_DIR = config["RAW_DIR"]
PROCESSED_DIR = config["PROCESSED_DIR"]
COMPRESSED_DIR = config["COMPRESSED_DIR"]
UNCOMPRESSED_DIR = config["UNCOMPRESSED_DIR"]

rule all:
    input:
        f"{PROCESSED_DIR}/{DATASET}/description.mpk"

rule prepare_data:
    input:
        py_script = f"data/scripts/{DATASET}/prepare_data.py",
    output:
        description = f"{PROCESSED_DIR}/{DATASET}/description.mpk"
    log:
        f".snakemake/logs/{DATASET}/prepare_data.log"
    shell:
        f"""
        mkdir -p {PROCESSED_DIR}/{DATASET}
        python data/scripts/{DATASET}/prepare_data.py --input_dir {RAW_DIR}/{DATASET} --output_dir {PROCESSED_DIR}/{DATASET}
        """

include: "../freeze.smk"
