from pathlib import Path

DATASET = "willett_shenoy"

TMP_DIR = config["TMP_DIR"]
RAW_DIR = config["RAW_DIR"]
PROCESSED_DIR = config["PROCESSED_DIR"]

# Download the dataset from datadryad
url = "https://datadryad.org/api/v2/datasets/doi%3A10.5061%2Fdryad.wh70rxwmv/download"

rule all:
    input:
        f"{PROCESSED_DIR}/{DATASET}/description.yaml"

# Rule that downloads the dataset from the internet using wget
rule download_all:
    output:
        f"{RAW_DIR}/{DATASET}/handwritingBCIData.tar.gz",
        f"{RAW_DIR}/{DATASET}/handwritingBCIData/readme.pdf"
    shell:
        f"""
        mkdir -p {TMP_DIR}/{DATASET}
        wget -O {TMP_DIR}/{DATASET}/{DATASET}.zip {url}
        unzip -d {TMP_DIR}/{DATASET} -o {RAW_DIR}/{DATASET}/{DATASET}.zip
        tar -xzf {TMP_DIR}/{DATASET}/handwritingBCIData.tar.gz -C {RAW_DIR}/{DATASET}
        """

rule prepare_data:
    input:
        f"{RAW_DIR}/{DATASET}/handwritingBCIData/readme.pdf",
        py_script = f"data/scripts/{DATASET}/prepare_data.py",
    output:
        f"{PROCESSED_DIR}/{DATASET}/description.yaml"
    shell:
        f"""
        mkdir -p {PROCESSED_DIR}/{DATASET}
        python3 {{input.py_script}} --input_dir {RAW_DIR}/{DATASET}/handwritingBCIData --output_dir {PROCESSED_DIR}/{DATASET}
        """

include: "../freeze.smk"