######################################################
# Perich & Miller (2018) 
######################################################

DATASET = "perich_miller"

RAW_DIR = config["RAW_DIR"]
PROCESSED_DIR = config["PROCESSED_DIR"]
COMPRESSED_DIR = config["COMPRESSED_DIR"]

rule all:
    input:
        f"{PROCESSED_DIR}/{DATASET}/description.yaml"

rule download_data:
    output: f"{RAW_DIR}/{DATASET}/ReachingData/Chewie_20131003_CO_VR_BL_001_stripped.mat",
    shell:
        f"""
        raise error "You must download the data manually from https://www.dropbox.com/home/Project%20Kirby"
        """

rule prepare_data:
    input:
        py_script = f"data/scripts/{DATASET}/prepare_data.py",
        mat_files = f"{RAW_DIR}/{DATASET}/ReachingData/Chewie_20131003_CO_VR_BL_001_stripped.mat",
    output:
        description = f"{PROCESSED_DIR}/{DATASET}/description.yaml"
    shell:
        f"""
        mkdir -p {PROCESSED_DIR}/{DATASET}
        python data/scripts/{DATASET}/prepare_data.py --input_dir {TMP_DIR}/raw/{DATASET} --output_dir {TMP_DIR}/processed/{DATASET}
        """

rule compress_data:
    input:
        description = f"{PROCESSED_DIR}/{DATASET}/description.yaml"
    output:
        train_tar = f"{COMPRESSED_DIR}/{DATASET}/train.tar.lz4",
        test_tar = f"{COMPRESSED_DIR}/{DATASET}/test.tar.lz4",
        valid_tar = f"{COMPRESSED_DIR}/{DATASET}/valid.tar.lz4",
        desc_out = f"{COMPRESSED_DIR}/{DATASET}/description.yaml"
    shell:
        f"""
        mkdir -p {COMPRESSED_DIR}/{DATASET}
        for split in train valid test; do
            # Single lz4 archive.
            cd {PROCESSED_DIR}/{DATASET}/$split && \
                tar -cf - . | lz4 -1 > {COMPRESSED_DIR}/{DATASET}/$split.tar.lz4
            cd - > /dev/null
            # Multiple shards for webdataset usage.
            python split_and_tar.py --input_dir "{PROCESSED_DIR}/{DATASET}/$split" --output_dir "{COMPRESSED_DIR}/{DATASET}" --prefix $split
        done
        cp {{input.description}} {COMPRESSED_DIR}/{DATASET}/description.yaml
        """
