######################################################
# Perich & Miller (2018) 
######################################################

DATASET = "perich_miller_population_2018"

RAW_DIR = config["RAW_DIR"]
PROCESSED_DIR = config["PROCESSED_DIR"]

rule all:
    input:
        f"{PROCESSED_DIR}/{DATASET}/description.mpk"

rule download_data:
    output: f"{RAW_DIR}/{DATASET}/ReachingData/Chewie_20131003_CO_VR_BL_001_stripped.mat",
    shell:
        f"""
        raise error "You must download the data manually from https://www.dropbox.com/home/Project%20Kirby"
        """

rule prepare_data:
    input:
        py_script = f"data/scripts/{DATASET}/prepare_data.py",
        mat_files = f"{RAW_DIR}/{DATASET}/ReachingData/Chewie_20131003_CO_VR_BL_001_stripped.mat",
    output:
        description = f"{PROCESSED_DIR}/{DATASET}/description.mpk"
    log:
        f".snakemake/logs/{DATASET}/prepare_data.log"
    shell:
        f"""
        mkdir -p {PROCESSED_DIR}/{DATASET}
        python data/scripts/{DATASET}/prepare_data.py --input_dir {RAW_DIR}/{DATASET} --output_dir {PROCESSED_DIR}/{DATASET}
        """

include: "../freeze.smk"